### ISSUE TITLE
Error when compiling terylene.go

### ISSUE THREAD

**Issue by TheDevAlive** [polymaster3313/terylene#1]
Error when compiling terylene.go

Tested on centos 7 and arch with same error following tutorial.
go version go1.21.1 linux/amd64

[birger@Rose terylene]$ cd mirai
[birger@Rose mirai]$ sudo go build -ldflags="-s -w" terylene.go
terylene.go:7:2: package zeroC2/mirai/components/system is not in std (/usr/lib/go/src/zeroC2/mirai/components/system)
terylene.go:8:2: package zeroC2/mirai/components/worm is not in std (/usr/lib/go/src/zeroC2/mirai/components/worm)
terylene.go:9:2: package zeroC2/mirai/ddos is not in std (/usr/lib/go/src/zeroC2/mirai/ddos)
[birger@Rose mirai]$

If there is any more info i can provide, please just ask.

**Comment by tcpfin-dev** [comment]
problem fixed, forgot to change the zeroC2/ to terylene/. Because my work environment is zeroC2. rm -r the old folder and git clone the new one, and follow the steps again.

![image](https://github.com/polymaster3313/terylene/assets/93959737/6ddbd8f4-2dcc-42bc-abbb-5e2656481d2b)

**Comment by tcpfin-dev** [comment]
PS: ive added a new feature for the worm, which allows it to spread through the internet. So you will have to put your C2 ip in the terylene/mirai/components/worm/localworm.go as well. Ill be adding a config file in the future so the setup wont be that messy
