### ISSUE TITLE
can't build server.go and terylene.go

### ISSUE THREAD

**Issue by NuxLO49** [polymaster3313/terylene#7]
root@zeroC2:~/project/terylene/server# go build server.go
# github.com/pebbe/zmq4
/root/go/pkg/mod/github.com/pebbe/zmq4@v1.2.10/reactor.go:10:4: undefined: State
/root/go/pkg/mod/github.com/pebbe/zmq4@v1.2.10/reactor.go:11:9: undefined: State
/root/go/pkg/mod/github.com/pebbe/zmq4@v1.2.10/reactor.go:21:16: undefined: Socket
/root/go/pkg/mod/github.com/pebbe/zmq4@v1.2.10/reactor.go:23:12: undefined: Poller
/root/go/pkg/mod/github.com/pebbe/zmq4@v1.2.10/reactor.go:61:34: undefined: Socket
/root/go/pkg/mod/github.com/pebbe/zmq4@v1.2.10/reactor.go:61:49: undefined: State
/root/go/pkg/mod/github.com/pebbe/zmq4@v1.2.10/reactor.go:68:37: undefined: Socket
/root/go/pkg/mod/github.com/pebbe/zmq4@v1.2.10/utils.go:17:12: undefined: Socket
/root/go/pkg/mod/github.com/pebbe/zmq4@v1.2.10/utils.go:24:12: undefined: Socket
/root/go/pkg/mod/github.com/pebbe/zmq4@v1.2.10/utils.go:28:12: undefined: Socket
/root/go/pkg/mod/github.com/pebbe/zmq4@v1.2.10/utils.go:28:12: too many errors

**Comment by polymaster3313** [comment]
Pebbe zmq4 is a binding for the C library zeromq. You did not even install the C library which is libzmq3-dev package


## For debian based distros
```
sudo apt-get update -y
sudo apt-get install -y libzmq3-dev
```

## for Arch based distros

```
sudo pacman -S zeromq
```

## for RHS based distros

```
sudo yum install -y zeromq-devel
```

**Comment by NuxLO49** [comment]
> Pebbe zmq4 is a binding for the C library zeromq. You did not even install the libzmq C library
> 
> ## For debian based distros
> ```
> sudo apt-get update -y
> sudo apt-get install -y libzmq3-dev
> ```
> 
> ## for Arch based distros
> ```
> sudo pacman -S zeromq
> ```
> 
> ## for RHS based distros
> ```
> sudo yum install -y zeromq-devel
> ```
