### ISSUE TITLE
can we add this as a attack method send router deauthentication packets to a website over the internet

### ISSUE THREAD

**Issue by s-b-repo** [polymaster3313/terylene#9]
this is just some basic code

package main

import (
	"fmt"
	"log"
	"net"
	"os"
	"os/exec"
	"runtime"
	"strings"
)

func main() {
	website := "example.com" // Replace with the target website

	// Resolve the IP address of the website
	ip, err := net.ResolveIPAddr("ip", website)
	if err != nil {
		fmt.Println(err)
		return
	}

	// Prepare the command based on the operating system
	var cmd *exec.Cmd
	switch runtime.GOOS {
	case "windows":
		cmd = exec.Command("cmd", "/C", "ping", "-n", "100", ip.String())
	case "linux", "darwin":
		cmd = exec.Command("ping", "-c", "100", ip.String())
	default:
		fmt.Println("Unsupported operating system")
		return
	}

	// Redirect the output to os.DevNull to hide it
	cmd.Stdout = os.DevNull
	cmd.Stderr = os.DevNull

	// Start the command execution
	err = cmd.Start()
	if err != nil {
		fmt.Println(err)
		return
	}

	fmt.Println("Sending deauthentication packets to", website)
	fmt.Println("To stop sending packets, press Ctrl+C")

	// Wait for the command to finish
	cmd.Wait()
}

**Comment by s-b-repo** [comment]
im not that good at go

**Comment by tcpfin-dev** [comment]
This is an ICMP flood method, however its better if you can code it so that it crafts the ICMP packet and sends it raw. Make a pull request if you have done so. And also ICMP flood is a layer 3 method, it cannot be used on websites.

**Comment by tcpfin-dev** [comment]
ICMP packet is definitely not a router deauthentication packet

**Comment by s-b-repo** [comment]
i googled what a router deauth packet should be is it possiple to send that type of packet other the internet

**Comment by tcpfin-dev** [comment]
deauthentication doesnt really overwelm the router, it actually just sends it to the users in a network as a "disconnect" signal from the router . Plus It makes no sense sending those packets over the internet because its a Layer 2 attack.

**Comment by tcpfin-dev** [comment]
Layer 2 packets are data link layer frames, and they are only designed to operate within a local network

**Comment by s-b-repo** [comment]
if someone manages to disconnect other users from their wifi over the internet how bad would the attack be

**Comment by tcpfin-dev** [comment]
the attack could usually be a UDP flood attack around 10gbps-15gbps. That amount of power is enough to down almost any type of routers.

**Comment by tcpfin-dev** [comment]
If you have nothing to say related to the topic. Then ill be closing the issue.
